# time interval: 1ns
# structure:
# data precision
data_pr: 16 # bit

# device level
ro: 16384
co: 32
co_w: 256 # bit
bg: 4
ba: 4
de_pu:
- 8
de_pu_bf: 2048 # 256 Byte
de_pu_inbuf: 2048 # 256 Byte
de_pu_bf_rl: 1 
de_pu_bf_wl: 1 
de_pu_w: # pu_parallelism, MM(oh,ow,v)
- 1
- 1
- 16
de_gb: 0 # 
de_gb_rl: 1
de_gb_wl: 1

# rank level: 8 device (ddr4)
de: 1
de_w: 64
ra_pu: 0
ra_pu_bf: 0 # 0
ra_pu_bf_rl: 1
ra_pu_bf_wl: 1

ra_gb: 0 # 
ra_gb_rl: 1
ra_gb_wl: 1 # 

# channel level (ddr4)
ra: 1
# system level
ch: 64 # 2*2*16
ch_w: 64
host_w: 
host_t: 
host_reduce_t: 

# Timing config (from gddr6)
tCCDL: 4
tCCDS: 2
tRCDWR: 10
tRCDRD: 14
tRP: 14
tWR: 16
tRTPL: 5
tWTRL: 9
tRTRS: 1
RL: 20
WL: 8
BL: 4